### PR TITLE
84 Remove Lincoln skin

### PR DESCRIPTION
**Pull request by jamiejordanmt**
https://trello.com/c/igJxa4Dg/84-remove-lincoln-skin

### CODE REVIEW

**Comment by jamiejordanmt** [comment]
I've left in the css file itself, as it will be useful for creating the new skin.

**Comment by jamiejordanmt** [comment]
[Remove Lincoln skin](https://trello.com/c/igJxa4Dg/84-remove-lincoln-skin)

**Comment by Bhavesh-Patel** [comment]
Should [Lincoln.scss](https://github.com/Newarkandsherwood/housing-repairs-online-frontend/blob/main/styles/lincoln.scss) be deleted also?

Has it intentionally not been deleted?

**Comment by jamiejordanmt** [comment]
> Should [Lincoln.scss](https://github.com/Newarkandsherwood/housing-repairs-online-frontend/blob/main/styles/lincoln.scss) be deleted also?
> 
> Has it intentionally not been deleted?

It was intentional, yes - see comment https://github.com/Newarkandsherwood/housing-repairs-online-frontend/pull/7#issuecomment-1164374025
but I have changed my mind as we know it's in source control and there is a possibility removing it will be forgotten later.

**Comment by jamiejordanmt** [comment]
> 



> Looks as I would expect
> 
> Might not be captured in this ticket but the accessibility link in the footer (it has no underline, or an affordance suggesting it's a link ) it links to Lincoln's accessibility statement.

The header and footer have been/will be captured in another ticket 👍

**Review by Bhavesh-Patel — APPROVED** [review]

**Pull request merged**
