### PR TITLE
172:: Change classes for conditional inputs

### PR DESCRIPTION
**Pull request by agnieszkazbikowska-madetech**

### CODE REVIEW

**Comment by agnieszkazbikowska-madetech** [comment]
[Change classes for conditional inputs.](https://trello.com/c/RBp7Vidc/172-change-classes-for-conditional-inputs)

**Review by markWarr — COMMENTED** [review]
Are we sure that the instances of the css class govuk-visually-hidden  in 

compoments/summaryList.js
and 
housing-repairs-online-frontend/compoments/footer.js

don't also need replacing?

**Comment by agnieszkazbikowska-madetech** [comment]
> Are we sure that the instances of the css class govuk-visually-hidden in
> 
> compoments/summaryList.js and housing-repairs-online-frontend/compoments/footer.js
> 
> don't also need replacing?

I've had a think about it and also added [a comment to the ticket](https://trello.com/c/RBp7Vidc/172-change-classes-for-conditional-inputs). I think that they're OK as they are, because they're not conditional. @Bhavesh-Patel is this correct?

**Comment by Bhavesh-Patel** [comment]
> > Are we sure that the instances of the css class govuk-visually-hidden in
> > compoments/summaryList.js and housing-repairs-online-frontend/compoments/footer.js
> > don't also need replacing?
> 
> I've had a think about it and also added [a comment to the ticket](https://trello.com/c/RBp7Vidc/172-change-classes-for-conditional-inputs). I think that they're OK as they are, because they're not conditional. @Bhavesh-Patel is this correct?

The other uses seem intentional for screen readers to read their contents.
I agree they should be left as they are.

**Review by Bhavesh-Patel — APPROVED** [review]

**Pull request merged**
